schedules:
  default:
    schedule: adhoc
    matrix:
      exclude:
        - java: openjdk6
          GUAVA: '21.0'
    env_vars: |
      TEST_GROUP="long"
env:
  GUAVA_VERSION:
    - '16.0.1'
    - '17.0'
    - '18.0'
    - '19.0'
    - '20.0'
    - '21.0'
java:
  - openjdk6
  - oraclejdk8
os:
  - ubuntu/trusty64
cassandra:
  - 3.9
build:
  - type: maven
    version: 3.2.5
    goals: install -DskipTests
  - type: maven
    version: 3.2.5
    goals: verify --fail-never -P$TEST_GROUP
    properties: |
      com.datastax.driver.TEST_BASE_NODE_WAIT=120
      com.datastax.driver.NEW_NODE_DELAY_SECONDS=100
      cassandra.version=$CCM_CASSANDRA_VERSION
      ccm.java.home=$CCM_JAVA_HOME
      ccm.path=$CCM_JAVA_HOME/bin
      ccm.maxNumberOfNodes=3
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
      guava.version=$GUAVA_VERSION
  - type: maven
    version: 3.2.5
    goals: verify --fail-never -Pisolated
    properties: |
      com.datastax.driver.TEST_BASE_NODE_WAIT=120
      com.datastax.driver.NEW_NODE_DELAY_SECONDS=100
      cassandra.version=$CCM_CASSANDRA_VERSION
      ccm.java.home=$CCM_JAVA_HOME
      ccm.path=$CCM_JAVA_HOME/bin
      ccm.maxNumberOfNodes=3
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
      guava.version=$GUAVA_VERSION
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml" 
